name: haskell-forest
version: 0.1.0.0
license: MIT
copyright: 2025 An Nyeong
maintainer: me@annyeong.me
author: An Nyeong
category: Web
language: GHC2021
extra-source-files:
  - LICENSE
  - README.md

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - NoStarIsType
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - StrictData
  - TypeFamilies
  - ViewPatterns

ghc-options:
  - -Wno-orphans
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wunused-foralls
  - -fprint-explicit-foralls
  - -fprint-explicit-kinds

dependencies:
  - aeson
  - async
  - name: base
    version: ">= 4 && < 5"
    mixin:
      - hiding (Prelude)
  - data-default
  - directory
  - errors
  - filepath
  - generic-lens
  - http-types
  - lens
  - mtl
  - optics-core
  - postgresql-simple
  - profunctors
  - name: relude
    version: ">= 1.0"
    mixin:
      - (Relude as Prelude, Relude.Container.One)
  - scotty
  - shower
  - stm
  - text
  - time
  - transformers
  - ulid
  - unliftio
  - wai
  - with-utf8

library:
  exposed: True
  source-dirs: src

executables:
  haskell-forest:
    main: Main.hs
    source-dirs: app
    dependencies:
      - haskell-forest
tests:
  haskell-forest-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-forest
      - hspec
      - QuickCheck
      - quickcheck-instances
